// Code generated by sqlc (manually included for a complete, compiling example).
package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5"
)

const listTodos = `
SELECT id, title, done, created_at
FROM todos
ORDER BY id DESC
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Todo
	for rows.Next() {
		var t Todo
		if err := rows.Scan(&t.ID, &t.Title, &t.Done, &t.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, t)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTodo = `
INSERT INTO todos (title)
VALUES ($1)
RETURNING id, title, done, created_at
`

type CreateTodoParams struct {
	Title string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title)
	var t Todo
	err := row.Scan(&t.ID, &t.Title, &t.Done, &t.CreatedAt)
	return t, err
}

// Ensure pgx.Row is referenced (keeps imports stable if regenerated).
var _ pgx.Row
